import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import { Header}  from "@/components/header"
import "./globals.css";
import { cn } from "@/lib/utils";
import Intro from "@/components/intro";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const uber = localFont({
  src: [
    { path: "../public/font/UberMoveMedium.otf", weight: "500" },
    { path: "../public/font/UberMoveBold.otf", weight: "700" },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("font-sans", geist.variable)}
    >
      <body className={cn(uber.className, "min-h-full flex flex-col")}>
        <Header></Header>
        <Intro></Intro>
        {children}
      </body>
    </html>
  );
}
