import type { Metadata } from "next";
import { Poppins, Geist } from "next/font/google";
import { Header}  from "@/components/header"
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("font-sans", geist.variable)}
    >
      <body className="min-h-full flex flex-col">
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
